import type { ComponentType, SVGProps } from "react";

import {
  Archive,
  Armchair,
  ArrowLeftRight,
  ArrowRight,
  Bath,
  Bed,
  Brush,
  Building,
  Building2,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Coffee,
  Coins,
  Crown,
  Disc,
  DoorClosed,
  Droplets,
  Facebook,
  Flame,
  Gem,
  HardHat,
  HeartHandshake,
  HelpCircle,
  Home,
  Instagram,
  Layers,
  Leaf,
  Linkedin,
  Lock,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Phone,
  PhoneCall,
  ShieldCheck,
  Snowflake,
  Sofa,
  Sparkles,
  Star,
  Sun,
  Truck,
  Users,
  Wind,
  Wrench,
  X,
  Youtube,
  type LucideProps
} from "lucide-react";

import { WhatsAppIcon } from "./WhatsAppIcon";

export const ICON_MAP: Record<string, ComponentType<LucideProps | SVGProps<SVGSVGElement>>> = {
  home: Home,
  building: Building2,
  "building-2": Building2,
  "building-office": Building,
  sparkles: Sparkles,
  sofa: Sofa,
  armchair: Armchair,
  bed: Bed,
  bath: Bath,
  monitor: Monitor,
  crown: Crown,
  coffee: Coffee,
  layers: Layers,
  flame: Flame,
  disc: Disc,
  brush: Brush,
  droplets: Droplets,
  sun: Sun,
  wind: Wind,
  snowflake: Snowflake,
  archive: Archive,
  "door-closed": DoorClosed,
  wrench: Wrench,
  "hard-hat": HardHat,
  truck: Truck,
  "shield-check": ShieldCheck,
  users: Users,
  leaf: Leaf,
  clock: Clock,
  coins: Coins,
  star: Star,
  gem: Gem,
  "heart-handshake": HeartHandshake,
  "map-pin": MapPin,
  phone: Phone,
  "phone-call": PhoneCall,
  mail: Mail,
  whatsapp: WhatsAppIcon as ComponentType<LucideProps | SVGProps<SVGSVGElement>>,
  facebook: Facebook,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  calendar: Calendar,
  lock: Lock,
  "arrow-right": ArrowRight,
  "arrow-left-right": ArrowLeftRight,
  check: Check,
  menu: Menu,
  x: X,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "help-circle": HelpCircle
};

export type IconName = keyof typeof ICON_MAP | string;

export interface JubuIconProps extends LucideProps {
  name: IconName;
}

export function JubuIcon({ name, ...props }: JubuIconProps) {
  const IconComponent = ICON_MAP[name.toLowerCase()] ?? HelpCircle;
  return <IconComponent {...props} />;
}
